name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend to Render
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_BE }}"

      - name: Deploy Frontend to Render
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_FE }}"
